import { OWS_BASE, DWD_WMS_BASE } from "./config.js";

export const CATEGORIES = [
  { id: "waldfunktionen", label: "Waldfunktionen",             icon: "🌲" },
  { id: "waldbiotope",    label: "Waldbiotope",                icon: "🌿" },
  { id: "standort",       label: "Forstliche Standortkarte",   icon: "🗺️" },
  { id: "wildtier",       label: "Wildtierökologie",           icon: "🦌" },
  { id: "klima",          label: "Klimafolgenforschung",       icon: "🌡️" },
  { id: "windenergie",    label: "Windenergie im Wald",        icon: "💨" },
  { id: "fernerkundung",  label: "Fernerkundung",              icon: "🛰️" },
  { id: "dwd",            label: "DWD Wetter & Klima",         icon: "☁️" },
  { id: "forstbw",        label: "ForstBW",                    icon: "🌳" },
  { id: "flurstücke",    label: "Flurstücke",                 icon: "📐" },
];

export const SERVICES = [

  // ─── WALDFUNKTIONEN ────────────────────────────────────────────────────────

  {
    id: "bodenschutzwald",
    category: "waldfunktionen",
    label: "Gesetzlicher Bodenschutzwald & Lawinenschutz",
    abstract: "Gesetzliche Bodenschutzwälder schützen gemäß § 30 LWaldG den Boden vor Erosion, Austrocknung und Verarmung. Die Lawinenschutzfunktion weist Wälder aus, die Siedlungen und Verkehrswege vor Schneebewegungen sichern.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Bodenschutzwald`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "bodenschutzwald", label: "Bodenschutzwald & Lawinenschutz", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 12,
  },

  {
    id: "erholungswald-stufen",
    category: "waldfunktionen",
    label: "Erholungswald Stufen 1 und 2",
    abstract: "Erholungswälder mit besonderer Bedeutung für die Naherholung. Stufe 1: sehr hoher Erholungsdruck (Verdichtungsräume), Stufe 2: erhöhter Erholungsbedarf.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Erholungswald_Stufe1und2`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "erholungswald", label: "Erholungswald Stufen 1 und 2", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 12,
  },

  {
    id: "erholungswald-gesetzlich",
    category: "waldfunktionen",
    label: "Gesetzlicher Erholungswald",
    abstract: "Nach § 33 LWaldG durch Rechtsverordnung ausgewiesene Erholungswälder. Höchste Schutz- und Pflegestufe.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Gesetzlicher_Erholungswald`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "gesetzlicher_erholungswald", label: "Gesetzlicher Erholungswald", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 12,
  },

  {
    id: "immissionsschutzwald",
    category: "waldfunktionen",
    label: "Immissionsschutzwald",
    abstract: "Wälder die Siedlungen, Erholungsgebiete oder landwirtschaftliche Nutzflächen vor schädlichen Luftverunreinigungen schützen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Immissionsschutzwald`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "immissionsschutzwald", label: "Immissionsschutzwald", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 12,
  },

  {
    id: "klimaschutzwald",
    category: "waldfunktionen",
    label: "Klimaschutzwald",
    abstract: "Wälder mit besonderer Bedeutung für den lokalen und regionalen Klimaschutz: Kaltluftproduktion, Frischluftschneisen, Temperaturausgleich.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Klimaschutzwald`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "klimaschutzwald", label: "Klimaschutzwald", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "static",
    license: "open-data",
    minZoom: 12,
  },

  {
    id: "sichtschutzwald",
    category: "waldfunktionen",
    label: "Sichtschutzwald",
    abstract: "Wälder die störende Anlagen oder Landschaftseingriffe visuell abschirmen und damit das Landschaftsbild schützen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Sichtschutzwald`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "sichtschutzwald", label: "Sichtschutzwald", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 12,
  },

  {
    id: "umweltschutzwald",
    category: "waldfunktionen",
    label: "Gesetzlicher Schutzwald gegen schädliche Umwelteinwirkungen",
    abstract: "Per Rechtsverordnung ausgewiesene Schutzwälder gemäß § 30 LWaldG, die Siedlungen vor schädlichen Einwirkungen schützen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Gesetzlicher_Umweltschutzwald`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "umweltschutzwald", label: "Umweltschutzwald", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 12,
  },

  {
    id: "wasserschutzwald",
    category: "waldfunktionen",
    label: "Sonstiger Wasserschutzwald",
    abstract: "Wälder in Wasserschutz- und Wassereinzugsgebieten mit Funktion für Grundwasserneubildung, Quellschutz und Hochwasserregulierung.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Wasserschutzwald`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "sonstiger_wasserschutzwald", label: "Wasserschutzwald", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 12,
  },

  // ─── WALDBIOTOPE ───────────────────────────────────────────────────────────

  {
    id: "waldbiotope",
    category: "waldbiotope",
    label: "Waldbiotope (Waldbiotopkartierung BW)",
    abstract: "Waldbiotopkartierung (WBK) der FVA: alle nach § 30 BNatSchG, § 32 NatSchG BW und § 30a LWaldG gesetzlich geschützten Biotope im Wald sowie Biotope die der Selbstbindung des Waldbesitzers unterliegen. In FFH-Gebieten zusätzlich Wald-Lebensraumtypen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Waldbiotope`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "waldbiotope", label: "Waldbiotope", defaultVisible: false },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "weekly",
    license: "fva-nutzungsbedingungen",
    minZoom: 12,
  },

  // ─── FORSTLICHE STANDORTKARTIERUNG ─────────────────────────────────────────

  {
    id: "standortskarte",
    category: "standort",
    label: "Forstliche Standortskarte",
    abstract: "Forstliche Standortskartierung: natürliche Standortbedingungen (Boden, Wasser, Klima) für die Waldbewirtschaftung. Maßstab 1:10.000. Grundlage für Baumartenwahl und Waldbauplanung.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Forstliche_Standortskarte`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "regional_zonale_standortseinheiten", label: "Standortseinheiten", defaultVisible: false },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 13,
  },

  {
    id: "regionale-gliederung",
    category: "standort",
    label: "Standortskundliche Regionale Gliederung",
    abstract: "Großräumige standortskundliche Gliederung Baden-Württembergs in Wuchsgebiete, Wuchsbezirke und Wuchsdistrikte. Grundlage für überregionale Waldplanung.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_RegionaleGliederung`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "regionale_zonalwaelder_klimahaupttyp", label: "Regionale Gliederung", defaultVisible: false },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 6,
  },

  // ─── WILDTIERÖKOLOGIE ──────────────────────────────────────────────────────

  {
    id: "generalwildwegeplan",
    category: "wildtier",
    label: "Generalwildwegeplan",
    abstract: "Landesweites Netz von Wildtierkorridoren und Lebensraumverbundachsen. Planungsgrundlage für Raumordnung, Straßenbau und Waldwirtschaft.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Generalwildwegeplan`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "Wildtierkorridor_1000m", label: "Wildtierkorridore", defaultVisible: false },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "static",
    license: "open-data",
  },

  {
    id: "rotwildgebiete",
    category: "wildtier",
    label: "Rotwildgebiete",
    abstract: "Offizielle Rotwildgebiete in Baden-Württemberg gemäß Rotwildkonzept. Lebensräume und Bewirtschaftungsräume des Rothirsches.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Rotwildgebiete`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "rotwildgebiete_baden_wuerttemberg", label: "Rotwildgebiete", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 6,
  },

  {
    id: "wildruhegebiete",
    category: "wildtier",
    label: "Wildruhegebiete",
    abstract: "Ausgewiesene Ruhezonen für störungsempfindliche Wildtierarten, insbesondere Auerhuhn und Luchs. Betreten oder Befahren saisonal oder ganzjährig eingeschränkt.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Wildruhegebiete`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "wildschutzgebiete_und_wildruhegebiete", label: "Wildruhegebiete", defaultVisible: false },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "wildkatzennachweise",
    category: "wildtier",
    label: "Wildkatzennachweise",
    abstract: "Kartierte Nachweise der Europäischen Wildkatze (Felis silvestris) in BW. Daten aus Monitoring-Programmen und Meldungen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Wildkatze`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "wildkatzennachweise", label: "Nachweise", defaultVisible: false },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "monthly",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "luchsnachweise",
    category: "wildtier",
    label: "Luchsnachweise",
    abstract: "Nachweise des Eurasischen Luchses (Lynx lynx) in BW im 10×10 km-Rasterformat. Auflösung absichtlich vergröbert um Störung von Individuen zu vermeiden.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Luchsnachweise`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "luchsnachweise_2016_2017", label: "Nachweise (10×10 km Raster)", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "monthly",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "wolfsnachweise",
    category: "wildtier",
    label: "Wolfsnachweise",
    abstract: "Dokumentierte Wolfsnachweise (Canis lupus) in BW. C1-Nachweise (genetisch gesichert) und C2-Nachweise (Sichtung/Riss). In Kooperation mit der LUBW.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Wolfsnachweise`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "wolfsnachweise_2016_2017", label: "Wolfsnachweise", defaultVisible: false },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "monthly",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "auerhuhn-flaechen",
    category: "wildtier",
    label: "Auerhuhnrelevante Flächen",
    abstract: "Auerhuhnrelevante Waldflächen in BW. Das Auerhuhn (Tetrao urogallus) ist in BW stark gefährdet. Grundlage für den Aktionsplan Auerhuhn des MLR BW.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_AuerhuhnFlaechen`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "prioritaere_flaechen", label: "Prioritäre Flächen", defaultVisible: false },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "monthly",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "auerhuhn-verbreitung",
    category: "wildtier",
    label: "Auerhuhnverbreitung",
    abstract: "Aktuelle Verbreitung des Auerhuhns (Tetrao urogallus) in BW (Stand 2023).",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Auerhuhnverbreitung`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "auerhuhnverbreitungsgebiet_2023", label: "Verbreitungsgebiet 2023", defaultVisible: false },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "monthly",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "auerhuhn-aktionsplan",
    category: "wildtier",
    label: "Aktionsplan Auerhuhn – Maßnahmenplan",
    abstract: "Konkrete Maßnahmenflächen aus dem Aktionsplan Auerhuhn BW. Prioritätsbereiche für Habitatverbesserung, Störungsreduzierung und Wiederansiedlungsprojekte.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Auerhuhn_Aktion_Massnahmenplan`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "Massnahmenplan_2023-202841109", label: "Maßnahmenplan", defaultVisible: false },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "monthly",
    license: "open-data",
  },

  {
    id: "windenergie-auerhuhn",
    category: "wildtier",
    label: "Windenergie und Auerhuhn",
    abstract: "Räumliche Überschneidung von Windenergie-Eignungsflächen mit Auerhuhn-Habitaten. Grundlage: FVA-Planungshinweis 'Windenergie und Auerhuhn'.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Auerhuhn_Windenergie`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "Windkraft_und_Auerhuhn14260", label: "Konfliktbereiche", defaultVisible: false },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "static",
    license: "open-data",
  },

  // ─── KLIMAFOLGENFORSCHUNG ──────────────────────────────────────────────────

  {
    id: "klima-buchdrucker",
    category: "klima",
    label: "Buchdruckergefährdung",
    abstract: "Räumliche Gefährdungskarte für Fichtenbestände durch den Buchdrucker (Ips typographus) unter verschiedenen Klimaszenarien. Basiert auf FVA-Klimafolgen-Modellen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Klima_Buchdruckergefaehrdung`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "buchdruckerrisiko_1981_2010",        label: "Referenz 1981–2010",      defaultVisible: false },
      { name: "buchdruckerrisiko_rcp45_2021_2050",  label: "RCP 4.5 (2021–2050)" },
      { name: "buchdruckerrisiko_rcp45_2071_2100",  label: "RCP 4.5 (2071–2100)" },
      { name: "buchdruckerrisiko_rcp85_2021_2050",  label: "RCP 8.5 (2021–2050)" },
      { name: "buchdruckerrisiko_rcp85_2071_2100",  label: "RCP 8.5 (2071–2100)" },
    ],
    featureInfoType: "value-only",
    chartComponent: "BuchdruckerChart",
    updateInterval: "daily",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "klima-bonitaet",
    category: "klima",
    label: "Bonität",
    abstract: "Veränderung der forstlichen Bonität (Wuchsleistung) wichtiger Baumarten unter Klimawandel-Szenarien. Grundlage: FVA-Klimakarten 2.1.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Klima_Bonitaet`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "ausgangsbonitaet_buche_current",                      label: "Buche – Heute",              defaultVisible: false },
      { name: "relative_bonitaetsveraenderung_buche_rcp45_2021_2050", label: "Buche – RCP 4.5 (2021–50)" },
      { name: "relative_bonitaetsveraenderung_buche_rcp45_2071_2100", label: "Buche – RCP 4.5 (2071–100)" },
      { name: "relative_bonitaetsveraenderung_buche_rcp85_2021_2050", label: "Buche – RCP 8.5 (2021–50)" },
      { name: "relative_bonitaetsveraenderung_buche_rcp85_2071_2100", label: "Buche – RCP 8.5 (2071–100)" },
      { name: "ausgangsbonitaet_eiche_current",                      label: "Eiche – Heute" },
      { name: "relative_bonitaetsveraenderung_eiche_rcp45_2021_2050", label: "Eiche – RCP 4.5 (2021–50)" },
      { name: "relative_bonitaetsveraenderung_eiche_rcp45_2071_2100", label: "Eiche – RCP 4.5 (2071–100)" },
      { name: "relative_bonitaetsveraenderung_eiche_rcp85_2021_2050", label: "Eiche – RCP 8.5 (2021–50)" },
      { name: "relative_bonitaetsveraenderung_eiche_rcp85_2071_2100", label: "Eiche – RCP 8.5 (2071–100)" },
      { name: "ausgangsbonitaet_fichte_current",                     label: "Fichte – Heute" },
      { name: "relative_bonitaetsveraenderung_fichte_rcp45_2021_2050", label: "Fichte – RCP 4.5 (2021–50)" },
      { name: "relative_bonitaetsveraenderung_fichte_rcp45_2071_2100", label: "Fichte – RCP 4.5 (2071–100)" },
      { name: "relative_bonitaetsveraenderung_fichte_rcp85_2021_2050", label: "Fichte – RCP 8.5 (2021–50)" },
      { name: "relative_bonitaetsveraenderung_fichte_rcp85_2071_2100", label: "Fichte – RCP 8.5 (2071–100)" },
      { name: "ausgangsbonitaet_tanne_current",                      label: "Tanne – Heute" },
      { name: "relative_bonitaetsveraenderung_tanne_rcp45_2021_2050", label: "Tanne – RCP 4.5 (2021–50)" },
      { name: "relative_bonitaetsveraenderung_tanne_rcp45_2071_2100", label: "Tanne – RCP 4.5 (2071–100)" },
      { name: "relative_bonitaetsveraenderung_tanne_rcp85_2021_2050", label: "Tanne – RCP 8.5 (2021–50)" },
      { name: "relative_bonitaetsveraenderung_tanne_rcp85_2071_2100", label: "Tanne – RCP 8.5 (2071–100)" },
    ],
    featureInfoType: "value-only",
    chartComponent: "ScenarioBar",
    scenarioRelative: true,
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "klima-sturm",
    category: "klima",
    label: "Sturmwurfgefährdung",
    abstract: "Räumliche Bewertung der Sturmwurfgefährdung von Waldbeständen unter Berücksichtigung von Bestandsstruktur, Standort und projizierten Windverhältnissen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Klima_Sturm`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "sturmschadensrisiko_real_buche_eiche",      label: "Risiko – Buche/Eiche",      defaultVisible: false },
      { name: "sturmschadensrisiko_real_fichte",           label: "Risiko – Fichte" },
      { name: "sturmschadensrisiko_real_tanne_douglasie",  label: "Risiko – Tanne/Douglasie" },
      { name: "sturmschadensrisiko_real_kiefer_laerche",   label: "Risiko – Kiefer/Lärche" },
      { name: "sturmschadensrisiko_real_andere_baumarten", label: "Risiko – Andere" },
      { name: "sturmschadenspotential_buche_eiche",        label: "Potential – Buche/Eiche" },
      { name: "sturmschadenspotential_fichte",             label: "Potential – Fichte" },
      { name: "sturmschadenspotential_tanne_douglasie",    label: "Potential – Tanne/Douglasie" },
    ],
    featureInfoType: "value-only",
    chartComponent: "ScenarioBar",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "klima-wasserhaushalt",
    category: "klima",
    label: "Bodenwasserhaushalt",
    abstract: "Modellierte Veränderungen im forstlichen Bodenwasserhaushalt unter Klimawandel. Trockenstress-Häufigkeit und Wasserverfügbarkeit für Waldbäume.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Klima_Wasserhaushalt`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "relative_bodenwassersaettigung_buche_1981_2010",       label: "Buche – Referenz 1981–2010", defaultVisible: false },
      { name: "relative_bodenwassersaettigung_buche_rcp45_2021_2050", label: "Buche – RCP 4.5 (2021–50)" },
      { name: "relative_bodenwassersaettigung_buche_rcp45_2071_2100", label: "Buche – RCP 4.5 (2071–100)" },
      { name: "relative_bodenwassersaettigung_buche_rcp85_2021_2050", label: "Buche – RCP 8.5 (2021–50)" },
      { name: "relative_bodenwassersaettigung_buche_rcp85_2071_2100", label: "Buche – RCP 8.5 (2071–100)" },
      { name: "relative_bodenwassersaettigung_fichte_1981_2010",      label: "Fichte – Referenz 1981–2010" },
      { name: "relative_bodenwassersaettigung_fichte_rcp45_2021_2050", label: "Fichte – RCP 4.5 (2021–50)" },
      { name: "relative_bodenwassersaettigung_fichte_rcp45_2071_2100", label: "Fichte – RCP 4.5 (2071–100)" },
      { name: "relative_bodenwassersaettigung_fichte_rcp85_2021_2050", label: "Fichte – RCP 8.5 (2021–50)" },
      { name: "relative_bodenwassersaettigung_fichte_rcp85_2071_2100", label: "Fichte – RCP 8.5 (2071–100)" },
    ],
    featureInfoType: "value-only",
    chartComponent: "ScenarioBar",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "klima-artverbreitung",
    category: "klima",
    label: "Artverbreitung",
    abstract: "Prognostizierte Verschiebung der Verbreitung wichtiger Baumarten in BW unter verschiedenen Klimaszenarien. Basiert auf Species Distribution Models (SDM).",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Klima_Artverbreitung`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "artverbreitung_buche_heute",            label: "Buche – Heute",              defaultVisible: false },
      { name: "artverbreitung_buche_rcp45_2041_2060",  label: "Buche – RCP 4.5 (2041–60)" },
      { name: "artverbreitung_buche_rcp45_2061_2080",  label: "Buche – RCP 4.5 (2061–80)" },
      { name: "artverbreitung_buche_rcp85_2041_2060",  label: "Buche – RCP 8.5 (2041–60)" },
      { name: "artverbreitung_buche_rcp85_2061_2080",  label: "Buche – RCP 8.5 (2061–80)" },
      { name: "artverbreitung_eiche_heute",            label: "Eiche – Heute" },
      { name: "artverbreitung_eiche_rcp45_2041_2060",  label: "Eiche – RCP 4.5 (2041–60)" },
      { name: "artverbreitung_eiche_rcp45_2061_2080",  label: "Eiche – RCP 4.5 (2061–80)" },
      { name: "artverbreitung_eiche_rcp85_2041_2060",  label: "Eiche – RCP 8.5 (2041–60)" },
      { name: "artverbreitung_eiche_rcp85_2061_2080",  label: "Eiche – RCP 8.5 (2061–80)" },
      { name: "artverbreitung_fichte_heute",           label: "Fichte – Heute" },
      { name: "artverbreitung_fichte_rcp45_2041_2060", label: "Fichte – RCP 4.5 (2041–60)" },
      { name: "artverbreitung_fichte_rcp45_2061_2080", label: "Fichte – RCP 4.5 (2061–80)" },
      { name: "artverbreitung_fichte_rcp85_2041_2060", label: "Fichte – RCP 8.5 (2041–60)" },
      { name: "artverbreitung_fichte_rcp85_2061_2080", label: "Fichte – RCP 8.5 (2061–80)" },
      { name: "artverbreitung_tanne_heute",            label: "Tanne – Heute" },
      { name: "artverbreitung_tanne_rcp45_2041_2060",  label: "Tanne – RCP 4.5 (2041–60)" },
      { name: "artverbreitung_tanne_rcp45_2061_2080",  label: "Tanne – RCP 4.5 (2061–80)" },
      { name: "artverbreitung_tanne_rcp85_2041_2060",  label: "Tanne – RCP 8.5 (2041–60)" },
      { name: "artverbreitung_tanne_rcp85_2061_2080",  label: "Tanne – RCP 8.5 (2061–80)" },
    ],
    featureInfoType: "value-only",
    chartComponent: "ScenarioBar",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "klima-vulnerabilitaet",
    category: "klima",
    label: "Vulnerabilität",
    abstract: "Synthetische Vulnerabilitätskarte für den Wald BW unter Klimawandel: kombiniert Exposition, Sensitivität und Anpassungskapazität.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Klima_Vulnerabilitaet`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "vulnerabilitaet_gesamt", label: "Gesamt",  defaultVisible: false },
      { name: "vulnerabilitaet_buche",  label: "Buche" },
      { name: "vulnerabilitaet_eiche",  label: "Eiche" },
      { name: "vulnerabilitaet_fichte", label: "Fichte" },
      { name: "vulnerabilitaet_tanne",  label: "Tanne" },
    ],
    featureInfoType: "value-only",
    chartComponent: "ScenarioBar",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
  },

  {
    id: "klima-baumarteneignung",
    category: "klima",
    label: "Baumarteneignung",
    abstract: "Klimatische Eignung verschiedener Baumarten für die Wiederbewaldung nach Störungen unter verschiedenen Klimaszenarien. Grundlage: FVA-Klimakarten 2.1.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Klima_Baumarteneignung_Klimawandel`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "baumarteneignung_bergahorn_heute",            label: "Bergahorn – Heute",          defaultVisible: false },
      { name: "baumarteneignung_bergahorn_rcp45_2041_2060",  label: "Bergahorn – RCP 4.5 (2041–60)" },
      { name: "baumarteneignung_bergahorn_rcp45_2061-2080",  label: "Bergahorn – RCP 4.5 (2061–80)" },
      { name: "baumarteneignung_bergahorn_rcp85_2041_2060",  label: "Bergahorn – RCP 8.5 (2041–60)" },
      { name: "baumarteneignung_bergahorn_rcp85_2061-2080",  label: "Bergahorn – RCP 8.5 (2061–80)" },
      { name: "baumarteneignung_buche_heute",                label: "Buche – Heute" },
      { name: "baumarteneignung_buche_rcp45_2021_2050",      label: "Buche – RCP 4.5 (2021–50)" },
      { name: "baumarteneignung_buche_rcp45_2071_2100",      label: "Buche – RCP 4.5 (2071–100)" },
      { name: "baumarteneignung_buche_rcp85_2021_2050",      label: "Buche – RCP 8.5 (2021–50)" },
      { name: "baumarteneignung_buche_rcp85_2071_2100",      label: "Buche – RCP 8.5 (2071–100)" },
      { name: "baumarteneignung_douglasie_heute",            label: "Douglasie – Heute" },
      { name: "baumarteneignung_douglasie_rcp45_2041_2060",  label: "Douglasie – RCP 4.5 (2041–60)" },
      { name: "baumarteneignung_douglasie_rcp45_2061-2080",  label: "Douglasie – RCP 4.5 (2061–80)" },
      { name: "baumarteneignung_douglasie_rcp85_2041_2060",  label: "Douglasie – RCP 8.5 (2041–60)" },
      { name: "baumarteneignung_douglasie_rcp85_2061-2080",  label: "Douglasie – RCP 8.5 (2061–80)" },
      { name: "baumarteneignung_eiche_heute",                label: "Eiche – Heute" },
      { name: "baumarteneignung_eiche_rcp45_2041_2060",      label: "Eiche – RCP 4.5 (2041–60)" },
      { name: "baumarteneignung_eiche_rcp45_2061-2080",      label: "Eiche – RCP 4.5 (2061–80)" },
      { name: "baumarteneignung_eiche_rcp85_2041_2060",      label: "Eiche – RCP 8.5 (2041–60)" },
      { name: "baumarteneignung_eiche_rcp85_2061-2080",      label: "Eiche – RCP 8.5 (2061–80)" },
      { name: "baumarteneignung_fichte_heute",               label: "Fichte – Heute" },
      { name: "baumarteneignung_fichte_rcp45_2021_2050",     label: "Fichte – RCP 4.5 (2021–50)" },
      { name: "baumarteneignung_fichte_rcp45_2071_2100",     label: "Fichte – RCP 4.5 (2071–100)" },
      { name: "baumarteneignung_fichte_rcp85_2021_2050",     label: "Fichte – RCP 8.5 (2021–50)" },
      { name: "baumarteneignung_fichte_rcp85_2071_2100",     label: "Fichte – RCP 8.5 (2071–100)" },
      { name: "baumarteneignung_tanne_heute",                label: "Tanne – Heute" },
      { name: "baumarteneignung_tanne_rcp45_2021_2050",      label: "Tanne – RCP 4.5 (2021–50)" },
      { name: "baumarteneignung_tanne_rcp45_2071_2100",      label: "Tanne – RCP 4.5 (2071–100)" },
      { name: "baumarteneignung_tanne_rcp85_2021_2050",      label: "Tanne – RCP 8.5 (2021–50)" },
      { name: "baumarteneignung_tanne_rcp85_2071_2100",      label: "Tanne – RCP 8.5 (2071–100)" },
      { name: "baumarteneignung_waldkiefer_heute",           label: "Waldkiefer – Heute" },
      { name: "baumarteneignung_waldkiefer_rcp45_2041_2060", label: "Waldkiefer – RCP 4.5 (2041–60)" },
      { name: "baumarteneignung_waldkiefer_rcp45_2061-2080", label: "Waldkiefer – RCP 4.5 (2061–80)" },
      { name: "baumarteneignung_waldkiefer_rcp85_2041_2060", label: "Waldkiefer – RCP 8.5 (2041–60)" },
      { name: "baumarteneignung_waldkiefer_rcp85_2061-2080", label: "Waldkiefer – RCP 8.5 (2061–80)" },
    ],
    featureInfoType: "value-only",
    chartComponent: "ScenarioBar",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
  },

  // ─── WINDENERGIE IM WALD ───────────────────────────────────────────────────

  {
    id: "windpotential-525",
    category: "windenergie",
    label: "Windenergiepotential Wald – 5,25 m/s in 100 m",
    abstract: "Potenzialstudie Windenergie im Wald BW: Flächen mit mittlerer Windgeschwindigkeit ≥ 5,25 m/s in 100 m Höhe. Untergrenze für wirtschaftlichen Betrieb kleiner Anlagen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Windenergiepotential_Wald_525ms_100m`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "windenergiepotential_wald_525ms_100m", label: "Potential ≥ 5,25 m/s", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 13,
  },

  {
    id: "windpotential-575",
    category: "windenergie",
    label: "Windenergiepotential Wald – 5,75 m/s in 100 m",
    abstract: "Potenzialstudie Windenergie im Wald BW: Flächen mit mittlerer Windgeschwindigkeit ≥ 5,75 m/s in 100 m Höhe. Mindestanforderung für moderne Großanlagen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Windenergiepotential_Wald_575ms_100m`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "windenergiepotential_wald_575ms_100m", label: "Potential ≥ 5,75 m/s", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    chartComponent: "RasterValue",
    updateInterval: "static",
    license: "fva-nutzungsbedingungen",
    minZoom: 13,
  },

  // ─── FERNERKUNDUNG ─────────────────────────────────────────────────────────

  {
    id: "laub-nadelwaldkarte",
    category: "fernerkundung",
    label: "Laub-Nadelwaldkarte",
    abstract: "Klassifikation des Waldes in Nadel-, Misch- und Laubwald auf Basis von Luftbild-Befliegungen. Jährliche Aktualisierung aus Befliegungen der letzten 3 Jahre.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Fernerkundung_Laub_Nadelwald`,
    wmsVersion: "1.1.1",
    layers: [
      { name: "fern_laubnadelwald", label: "Waldtyp (Laub / Misch / Nadel)", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    updateInterval: "monthly",
    license: "open-data",
  },

  {
    id: "waldhoehen",
    category: "fernerkundung",
    label: "Waldhöhenstrukturkarte",
    abstract: "Karte der Waldhöhenstruktur aus normalisierten Höhenmodellen (nDSMs), berechnet aus Luftbild-Befliegungen. Zeigt Bestandeshöhen und vertikale Waldstruktur.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Fernerkundung_Waldhoehenstruktur`,
    wmsVersion: "1.1.1",
    layers: [
      { name: "fern_whsk", label: "Bestandeshöhe", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    updateInterval: "monthly",
    license: "open-data",
  },

  {
    id: "baumbedeckung",
    category: "fernerkundung",
    label: "Baumbedeckung",
    abstract: "Identifikation von Einzelbäumen innerhalb und außerhalb des Waldes aus Luftbildbefliegungen. Grundlage für Biodiversitätsmonitoring und Stadtbaum-Kartierungen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Fernerkundung_Baumbedeckung`,
    wmsVersion: "1.1.1",
    layers: [
      { name: "fern_baumlayer", label: "Baumbedeckung", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    updateInterval: "monthly",
    license: "open-data",
  },

  {
    id: "waldbedeckung",
    category: "fernerkundung",
    label: "Waldbedeckung",
    abstract: "Binäre Klassifikation Wald / Nicht-Wald aus Luftbildauswertung. Aktueller und genauer als das amtliche Liegenschaftskataster für dynamische Waldgrenzveränderungen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Fernerkundung_Waldbedeckung`,
    wmsVersion: "1.1.1",
    layers: [
      { name: "fern_waldbedeckung", label: "Waldbedeckung", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    updateInterval: "monthly",
    license: "open-data",
  },

  {
    id: "waldbestockung",
    category: "fernerkundung",
    label: "Waldbestockung",
    abstract: "Differenziertere Klassifikation des Waldes nach Bestockungsgrad und Struktur. Unterscheidet z.B. Bestandswald, Verjüngungsflächen und Windwurfflächen.",
    wmsUrl: `${OWS_BASE}/WMS_FVA_Fernerkundung_Waldbestockung`,
    wmsVersion: "1.1.1",
    layers: [
      { name: "fern_bestockungslayer", label: "Waldbestockung", defaultVisible: false },
    ],
    featureInfoType: "value-only",
    updateInterval: "monthly",
    license: "open-data",
  },

  // ─── DWD WETTER & KLIMA ────────────────────────────────────────────────────

  {
    id: "dwd-bodenfeuchte",
    category: "dwd",
    label: "Bodenfeuchte (LWF-Brook90-Modell)",
    abstract: "Tägliche, modellierte Bodenfeuchte für verschiedene Baumarten (LWF-Brook90-Modell). Auflösung 1×1 km, ab 1991. Wert: % der nutzbaren Feldkapazität (nFK).",
    wmsUrl: DWD_WMS_BASE,
    wmsVersion: "1.3.0",
    layers: [
      { name: "GRD_DEU_P1D_BF-BUC", label: "Buche",  defaultVisible: false },
      { name: "GRD_DEU_P1D_BF-FIC", label: "Fichte" },
      { name: "GRD_DEU_P1D_BF-EIC", label: "Eiche" },
      { name: "GRD_DEU_P1D_BF-KIE", label: "Kiefer" },
    ],
    featureInfoType: "value-only",
    chartComponent: "BodenfeuchteChart",
    dataSource: { type: "wms-multi" },
    valueScale: 0.1,
    updateInterval: "daily",
    license: "open-data",
  },

  // ─── KATASTER ──────────────────────────────────────────────────────────────

  {
    id: "forstbezirke",
    category: "forstbw",
    label: "Forstbezirke (ForstBW)",
    abstract: "Forstliche Bewirtschaftungsgebiete und Forstbezirke in Baden-Württemberg. Quelle: ForstBW. Lizenz: CC BY-SA 4.0.",
    wmsUrl: `${OWS_BASE}/WMS_ForstBW_NachhaltWaldwirtschaft`,
    wmsVersion: "1.3.0",
    layers: [
      { name: "Betriebe",           label: "Betriebe",           defaultVisible: false, sidebarFilter: { field: "FBEZ", placeholder: "Forstbezirk filtern…" } },
      { name: "Bestaende",          label: "Bestände" },
      { name: "Waldrefugien",       label: "Waldrefugien" },
      { name: "Habitatbaumgruppen", label: "Habitatbaumgruppen" },
    ],
    featureInfoType: "geojson",
    chartComponent: "FeatureTable",
    updateInterval: "monthly",
    license: "open-data",
  },

  {
    id: "flurstuecke",
    category: "flurstücke",
    label: "Flurstücke (ALKIS/LGL)",
    abstract: "Amtliche Flurstücke aus dem ALKIS-Datenbestand des LGL BW. Open Data, keine Eigentümerdaten.",
    wmsUrl: `${OWS_BASE}/WMS_INSP_BW_Flst_ALKIS`,
    wfsUrl: "https://owsproxy.lgl-bw.de/owsproxy/wfs/WFS_INSP_BW_Flst_ALKIS",
    wmsVersion: "1.3.0",
    layers: [
      { name: "alkis:CP.CadastralParcel", label: "Flurstücke", defaultVisible: false },
    ],
    featureInfoType: "none",
    chartComponent: "FeatureTable",
    updateInterval: "monthly",
    license: "open-data",
    minZoom: 14,
  },

];

export function getServicesByCategory(categoryId) {
  return SERVICES.filter(s => s.category === categoryId);
}

export function getServiceById(id) {
  return SERVICES.find(s => s.id === id);
}
